"""Add Ticket model and last_email_at to accounts

Revision ID: 1c678d9a8fd8
Revises: 424290c90af7
Create Date: 2026-05-02 18:33:53.311798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c678d9a8fd8'
down_revision: Union[str, Sequence[str], None] = '424290c90af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('streaming_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_email_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_accounts', schema=None) as batch_op:
        batch_op.drop_column('last_email_at')

    op.drop_table('tickets')
    # ### end Alembic commands ###
