"""Add is_trial to streaming accounts

Revision ID: 424290c90af7
Revises: 6426039a64fc
Create Date: 2026-04-25 11:05:52.414130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '424290c90af7'
down_revision: Union[str, Sequence[str], None] = '6426039a64fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trial', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streaming_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_trial')

    # ### end Alembic commands ###
