"""Initial baseline

Revision ID: 6426039a64fc
Revises: 
Create Date: 2026-04-25 11:03:32.210014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6426039a64fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('owner_id',
                   existing_type=sa.BIGINT(),
                   nullable=True)

    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=20),
                   type_=sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'),
                   existing_nullable=False,
                   existing_server_default=sa.text("'ACTIVE'"))

    with op.batch_alter_table('sellers', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=10),
                   type_=sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'),
                   existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_end_date', sa.DATETIME(), nullable=False))
    op.alter_column('sellers', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('sellers', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('owners', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', name='statusenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('admins', 'owner_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
